import static org.junit.Assert.assertEquals;

import cs5004.animator.model.AnimationModelImpl;
import cs5004.animator.model.AnimationModelInterface;
import cs5004.animator.util.AnimationBuilder;
import cs5004.animator.util.AnimationReader;
import cs5004.animator.view.SVGView;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import org.junit.Before;
import org.junit.Test;

/**
 * This class represents a Junit test for a SvgTest class.
 */
public class SvgTest {
  AnimationModelInterface model;
  AnimationBuilder<AnimationModelInterface> builder;
  SVGView svgView;
  Appendable out;
  String filePath = new File("").getAbsolutePath();

  @Before
  public void setUp() {
    model = new AnimationModelImpl();
    svgView = new SVGView(out);
    builder = new AnimationModelImpl.Builder();
  }

  @Test (expected = FileNotFoundException.class)
    public void testFileNotFound() throws IOException {
    Appendable out = new FileWriter("svgTest1.txt");
    svgView = new SVGView(out);
    Readable readable = new FileReader(filePath + "/res/" + "smallldemo.txt");
    model = (AnimationModelImpl) AnimationReader.parseFile(readable, builder);
    svgView.show(model);
  }

  @Test (expected = IllegalArgumentException.class)
  public void testNullException() throws IOException {
    Appendable out = new FileWriter("svgTest1.txt");
    svgView = new SVGView(out);
    svgView.show(null);
  }


  @Test
  public void testSvgSmallDemo() throws IOException {
    Appendable out = new FileWriter("svgTest1.txt");
    svgView = new SVGView(out);
    Readable readable = new FileReader(filePath + "/res/" + "smalldemo.txt");
    model = (AnimationModelImpl) AnimationReader.parseFile(readable, builder);
    svgView.show(model);
    File file = new File("svgTest1.txt");
    FileReader read = new FileReader(file);
    char[] chars = new char[(int) file.length()];
    read.read(chars);
    String fileContent = new String(chars);
    assertEquals("<svg width=\"800\" height=\"800\" version=\"1.1\"\n"
        + "xmlns=\"http://www.w3.org/2000/svg\">\n"
        + "<rect id=\"R\" x=\"300.0\" y=\"300.0\" width=\"25.0\" height=\"100.0\" "
        + "fill=\"rgb(255,0,0)\" visibility=\"visible\">\n"
        + "<animate attributeType=\"xml\" begin=\"7000ms\" dur=\"3000ms\" attributeName=\"x\" "
        + "from=\"300.0\" to=\"200.0\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"7000ms\" dur=\"3000ms\" attributeName=\"y\" "
        + "from=\"300.0\" to=\"200.0\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"7000ms\" dur=\"3000ms\" "
        + "attributeName=\"height\" from=\"100\" to=\"100\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"7000ms\" dur=\"3000ms\" attributeName=\"width\" "
        + "from=\"25\" to=\"25\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"7000ms\" dur=\"3000ms\" attributeName=\"rgb\" "
        + "from=\"(255,0,0)\" to=\"(255,0,0)\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"5100ms\" dur=\"1900ms\" attributeName=\"x\" "
        + "from=\"300.0\" to=\"300.0\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"5100ms\" dur=\"1900ms\" attributeName=\"y\" "
        + "from=\"300.0\" to=\"300.0\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"5100ms\" dur=\"1900ms\" attributeName=\"height\" "
        + "from=\"100\" to=\"100\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"5100ms\" dur=\"1900ms\" attributeName=\"width\" "
        + "from=\"50\" to=\"25\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"5100ms\" dur=\"1900ms\" attributeName=\"rgb\" "
        + "from=\"(255,0,0)\" to=\"(255,0,0)\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"5000ms\" dur=\"100ms\" attributeName=\"x\" "
        + "from=\"300.0\" to=\"300.0\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"5000ms\" dur=\"100ms\" attributeName=\"y\" "
        + "from=\"300.0\" to=\"300.0\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"5000ms\" dur=\"100ms\" attributeName=\"height\""
        + " from=\"100\" to=\"100\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"5000ms\" dur=\"100ms\" attributeName=\"width\" "
        + "from=\"50\" to=\"50\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"5000ms\" dur=\"100ms\" attributeName=\"rgb\" "
        + "from=\"(255,0,0)\" to=\"(255,0,0)\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"1000ms\" dur=\"4000ms\" attributeName=\"x\" "
        + "from=\"200.0\" to=\"300.0\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"1000ms\" dur=\"4000ms\" attributeName=\"y\" "
        + "from=\"200.0\" to=\"300.0\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"1000ms\" dur=\"4000ms\" attributeName=\"height\""
        + " from=\"100\" to=\"100\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"1000ms\" dur=\"4000ms\" attributeName=\"width\" "
        + "from=\"50\" to=\"50\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"1000ms\" dur=\"4000ms\" attributeName=\"rgb\" "
        + "from=\"(255,0,0)\" to=\"(255,0,0)\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"100ms\" dur=\"900ms\" attributeName=\"x\" "
        + "from=\"200.0\" to=\"200.0\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"100ms\" dur=\"900ms\" attributeName=\"y\" "
        + "from=\"200.0\" to=\"200.0\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"100ms\" dur=\"900ms\" attributeName=\"height\" "
        + "from=\"100\" to=\"100\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"100ms\" dur=\"900ms\" attributeName=\"width\" "
        + "from=\"50\" to=\"50\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"100ms\" dur=\"900ms\" attributeName=\"rgb\" "
        + "from=\"(255,0,0)\" to=\"(255,0,0)\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "</rect>\n"
        + "<ellipse id=\"C\" cx=\"440.0\" cy=\"370.0\" rx=\"120.0\" ry=\"60.0\" "
        + "fill=\"rgb(0,255,0)\" visibility=\"visible\">\n"
        + "<animate attributeType=\"xml\" begin=\"8000ms\" dur=\"2000ms\" attributeName=\"cx\" "
        + "from=\"440.0\" to=\"440.0\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"8000ms\" dur=\"2000ms\" attributeName=\"cy\" "
        + "from=\"370.0\" to=\"370.0\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"8000ms\" dur=\"2000ms\" attributeName=\"ry\" "
        + "from=\"60\" to=\"60\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"8000ms\" dur=\"2000ms\" attributeName=\"rx\" "
        + "from=\"120\" to=\"120\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"8000ms\" dur=\"2000ms\" attributeName=\"rgb\" "
        + "from=\"(0,255,0)\" to=\"(0,255,0)\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"7000ms\" dur=\"1000ms\" attributeName=\"cx\" "
        + "from=\"440.0\" to=\"440.0\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"7000ms\" dur=\"1000ms\" attributeName=\"cy\" "
        + "from=\"370.0\" to=\"370.0\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"7000ms\" dur=\"1000ms\" attributeName=\"ry\" "
        + "from=\"60\" to=\"60\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"7000ms\" dur=\"1000ms\" attributeName=\"rx\" "
        + "from=\"120\" to=\"120\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"7000ms\" dur=\"1000ms\" attributeName=\"rgb\" "
        + "from=\"(0,170,85)\" to=\"(0,255,0)\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"5000ms\" dur=\"2000ms\" attributeName=\"cx\" "
        + "from=\"440.0\" to=\"440.0\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"5000ms\" dur=\"2000ms\" attributeName=\"cy\" "
        + "from=\"250.0\" to=\"370.0\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"5000ms\" dur=\"2000ms\" attributeName=\"ry\" "
        + "from=\"60\" to=\"60\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"5000ms\" dur=\"2000ms\" attributeName=\"rx\" "
        + "from=\"120\" to=\"120\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"5000ms\" dur=\"2000ms\" attributeName=\"rgb\" "
        + "from=\"(0,0,255)\" to=\"(0,170,85)\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"2000ms\" dur=\"3000ms\" attributeName=\"cx\" "
        + "from=\"440.0\" to=\"440.0\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"2000ms\" dur=\"3000ms\" attributeName=\"cy\" "
        + "from=\"70.0\" to=\"250.0\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"2000ms\" dur=\"3000ms\" attributeName=\"ry\" "
        + "from=\"60\" to=\"60\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"2000ms\" dur=\"3000ms\" attributeName=\"rx\" "
        + "from=\"120\" to=\"120\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"2000ms\" dur=\"3000ms\" attributeName=\"rgb\" "
        + "from=\"(0,0,255)\" to=\"(0,0,255)\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"600ms\" dur=\"1400ms\" attributeName=\"cx\" "
        + "from=\"440.0\" to=\"440.0\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"600ms\" dur=\"1400ms\" attributeName=\"cy\" "
        + "from=\"70.0\" to=\"70.0\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"600ms\" dur=\"1400ms\" attributeName=\"ry\" "
        + "from=\"60\" to=\"60\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"600ms\" dur=\"1400ms\" attributeName=\"rx\" "
        + "from=\"120\" to=\"120\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"600ms\" dur=\"1400ms\" attributeName=\"rgb\" "
        + "from=\"(0,0,255)\" to=\"(0,0,255)\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "</ellipse>\n"
        + "\n"
        + "</svg>", fileContent);
  }

  @Test
  public void testSvgToh3() throws IOException {
    Appendable out = new FileWriter("svgTest2.txt");
    svgView = new SVGView(out);
    Readable readable = new FileReader(filePath + "/res/" + "toh-3.txt");
    model = (AnimationModelImpl) AnimationReader.parseFile(readable, builder);
    svgView.show(model);
    File file = new File("svgTest2.txt");
    FileReader read = new FileReader(file);
    char[] chars = new char[(int) file.length()];
    read.read(chars);
    String fileContent = new String(chars);
    assertEquals("<svg width=\"800\" height=\"800\" version=\"1.1\"\n"
        + "xmlns=\"http://www.w3.org/2000/svg\">\n"
        + "<rect id=\"disk1\" x=\"490.0\" y=\"180.0\" width=\"20.0\" height=\"30.0\" "
        + "fill=\"rgb(0,255,0)\" visibility=\"visible\">\n"
        + "<animate attributeType=\"xml\" begin=\"25700ms\" dur=\"4500ms\" attributeName=\"x\" "
        + "from=\"490.0\" to=\"490.0\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"25700ms\" dur=\"4500ms\" attributeName=\"y\" "
        + "from=\"180.0\" to=\"180.0\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"25700ms\" dur=\"4500ms\" "
        + "attributeName=\"height\" from=\"30\" to=\"30\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"25700ms\" dur=\"4500ms\" "
        + "attributeName=\"width\" from=\"20\" to=\"20\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"25700ms\" dur=\"4500ms\" "
        + "attributeName=\"rgb\" from=\"(0,255,0)\" to=\"(0,255,0)\" "
        + "fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"24900ms\" dur=\"800ms\" attributeName=\"x\" "
        + "from=\"490.0\" to=\"490.0\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"24900ms\" dur=\"800ms\" attributeName=\"y\" "
        + "from=\"180.0\" to=\"180.0\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"24900ms\" dur=\"800ms\" attributeName=\"height\" "
        + "from=\"30\" to=\"30\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"24900ms\" dur=\"800ms\" attributeName=\"width\""
        + " from=\"20\" to=\"20\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"24900ms\" dur=\"800ms\" attributeName=\"rgb\""
        + " from=\"(0,49,90)\" to=\"(0,255,0)\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"23900ms\" dur=\"1000ms\" attributeName=\"x\" "
        + "from=\"490.0\" to=\"490.0\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"23900ms\" dur=\"1000ms\" attributeName=\"y\" "
        + "from=\"50.0\" to=\"180.0\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"23900ms\" dur=\"1000ms\" attributeName=\"height\""
        + " from=\"30\" to=\"30\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"23900ms\" dur=\"1000ms\" attributeName=\"width\""
        + " from=\"20\" to=\"20\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"23900ms\" dur=\"1000ms\" attributeName=\"rgb\""
        + " from=\"(0,49,90)\" to=\"(0,49,90)\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"23800ms\" dur=\"100ms\" attributeName=\"x\" "
        + "from=\"490.0\" to=\"490.0\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"23800ms\" dur=\"100ms\" attributeName=\"y\" "
        + "from=\"50.0\" to=\"50.0\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"23800ms\" dur=\"100ms\" attributeName=\"height\" "
        + "from=\"30\" to=\"30\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"23800ms\" dur=\"100ms\" attributeName=\"width\" "
        + "from=\"20\" to=\"20\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"23800ms\" dur=\"100ms\" attributeName=\"rgb\" "
        + "from=\"(0,49,90)\" to=\"(0,49,90)\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"22800ms\" dur=\"1000ms\" attributeName=\"x\" "
        + "from=\"190.0\" to=\"490.0\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"22800ms\" dur=\"1000ms\" attributeName=\"y\" "
        + "from=\"50.0\" to=\"50.0\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"22800ms\" dur=\"1000ms\" "
        + "attributeName=\"height\" from=\"30\" to=\"30\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"22800ms\" dur=\"1000ms\" attributeName=\"width\" "
        + "from=\"20\" to=\"20\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"22800ms\" dur=\"1000ms\" attributeName=\"rgb\""
        + " from=\"(0,49,90)\" to=\"(0,49,90)\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"22700ms\" dur=\"100ms\" attributeName=\"x\" "
        + "from=\"190.0\" to=\"190.0\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"22700ms\" dur=\"100ms\" attributeName=\"y\" "
        + "from=\"50.0\" to=\"50.0\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"22700ms\" dur=\"100ms\" attributeName=\"height\" "
        + "from=\"30\" to=\"30\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"22700ms\" dur=\"100ms\" attributeName=\"width\""
        + " from=\"20\" to=\"20\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"22700ms\" dur=\"100ms\" attributeName=\"rgb\""
        + " from=\"(0,49,90)\" to=\"(0,49,90)\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"21700ms\" dur=\"1000ms\" attributeName=\"x\" "
        + "from=\"190.0\" to=\"190.0\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"21700ms\" dur=\"1000ms\" attributeName=\"y\""
        + " from=\"240.0\" to=\"50.0\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"21700ms\" dur=\"1000ms\" attributeName=\"height\" "
        + "from=\"30\" to=\"30\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"21700ms\" dur=\"1000ms\" attributeName=\"width\" "
        + "from=\"20\" to=\"20\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"21700ms\" dur=\"1000ms\" attributeName=\"rgb\" "
        + "from=\"(0,49,90)\" to=\"(0,49,90)\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"18500ms\" dur=\"3200ms\" attributeName=\"x\" "
        + "from=\"190.0\" to=\"190.0\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"18500ms\" dur=\"3200ms\" attributeName=\"y\" "
        + "from=\"240.0\" to=\"240.0\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"18500ms\" dur=\"3200ms\" "
        + "attributeName=\"height\" from=\"30\" to=\"30\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"18500ms\" dur=\"3200ms\" attributeName=\"width\" "
        + "from=\"20\" to=\"20\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"18500ms\" dur=\"3200ms\" attributeName=\"rgb\""
        + " from=\"(0,49,90)\" to=\"(0,49,90)\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"17500ms\" dur=\"1000ms\" attributeName=\"x\" "
        + "from=\"190.0\" to=\"190.0\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"17500ms\" dur=\"1000ms\" attributeName=\"y\" "
        + "from=\"50.0\" to=\"240.0\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"17500ms\" dur=\"1000ms\" attributeName=\"height\" "
        + "from=\"30\" to=\"30\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"17500ms\" dur=\"1000ms\" attributeName=\"width\" "
        + "from=\"20\" to=\"20\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"17500ms\" dur=\"1000ms\" attributeName=\"rgb\" "
        + "from=\"(0,49,90)\" to=\"(0,49,90)\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"17400ms\" dur=\"100ms\" attributeName=\"x\" "
        + "from=\"190.0\" to=\"190.0\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"17400ms\" dur=\"100ms\" attributeName=\"y\" "
        + "from=\"50.0\" to=\"50.0\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"17400ms\" dur=\"100ms\" attributeName=\"height\" "
        + "from=\"30\" to=\"30\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"17400ms\" dur=\"100ms\" attributeName=\"width\" "
        + "from=\"20\" to=\"20\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"17400ms\" dur=\"100ms\" attributeName=\"rgb\" "
        + "from=\"(0,49,90)\" to=\"(0,49,90)\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"16400ms\" dur=\"1000ms\" attributeName=\"x\" "
        + "from=\"340.0\" to=\"190.0\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"16400ms\" dur=\"1000ms\" attributeName=\"y\" "
        + "from=\"50.0\" to=\"50.0\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"16400ms\" dur=\"1000ms\" attributeName=\"height\""
        + " from=\"30\" to=\"30\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"16400ms\" dur=\"1000ms\" attributeName=\"width\" "
        + "from=\"20\" to=\"20\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"16400ms\" dur=\"1000ms\" attributeName=\"rgb\" "
        + "from=\"(0,49,90)\" to=\"(0,49,90)\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"16300ms\" dur=\"100ms\" attributeName=\"x\" "
        + "from=\"340.0\" to=\"340.0\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"16300ms\" dur=\"100ms\" attributeName=\"y\""
        + " from=\"50.0\" to=\"50.0\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"16300ms\" dur=\"100ms\" attributeName=\"height\" "
        + "from=\"30\" to=\"30\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"16300ms\" dur=\"100ms\" attributeName=\"width\""
        + " from=\"20\" to=\"20\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"16300ms\" dur=\"100ms\" attributeName=\"rgb\" "
        + "from=\"(0,49,90)\" to=\"(0,49,90)\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"15300ms\" dur=\"1000ms\" attributeName=\"x\" "
        + "from=\"340.0\" to=\"340.0\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"15300ms\" dur=\"1000ms\" attributeName=\"y\" "
        + "from=\"210.0\" to=\"50.0\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"15300ms\" dur=\"1000ms\" attributeName=\"height\""
        + " from=\"30\" to=\"30\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"15300ms\" dur=\"1000ms\" attributeName=\"width\" "
        + "from=\"20\" to=\"20\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"15300ms\" dur=\"1000ms\" attributeName=\"rgb\" "
        + "from=\"(0,49,90)\" to=\"(0,49,90)\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"12100ms\" dur=\"3200ms\" attributeName=\"x\" "
        + "from=\"340.0\" to=\"340.0\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"12100ms\" dur=\"3200ms\" attributeName=\"y\" "
        + "from=\"210.0\" to=\"210.0\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"12100ms\" dur=\"3200ms\" attributeName=\"height\" "
        + "from=\"30\" to=\"30\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"12100ms\" dur=\"3200ms\" attributeName=\"width\""
        + " from=\"20\" to=\"20\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"12100ms\" dur=\"3200ms\" attributeName=\"rgb\" "
        + "from=\"(0,49,90)\" to=\"(0,49,90)\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"11100ms\" dur=\"1000ms\" attributeName=\"x\" "
        + "from=\"340.0\" to=\"340.0\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"11100ms\" dur=\"1000ms\" attributeName=\"y\" "
        + "from=\"50.0\" to=\"210.0\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"11100ms\" dur=\"1000ms\" attributeName=\"height\""
        + " from=\"30\" to=\"30\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"11100ms\" dur=\"1000ms\" attributeName=\"width\" "
        + "from=\"20\" to=\"20\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"11100ms\" dur=\"1000ms\" attributeName=\"rgb\""
        + " from=\"(0,49,90)\" to=\"(0,49,90)\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"11000ms\" dur=\"100ms\" attributeName=\"x\" "
        + "from=\"340.0\" to=\"340.0\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"11000ms\" dur=\"100ms\" attributeName=\"y\" "
        + "from=\"50.0\" to=\"50.0\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"11000ms\" dur=\"100ms\" attributeName=\"height\" "
        + "from=\"30\" to=\"30\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"11000ms\" dur=\"100ms\" attributeName=\"width\""
        + " from=\"20\" to=\"20\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"11000ms\" dur=\"100ms\" attributeName=\"rgb\" "
        + "from=\"(0,49,90)\" to=\"(0,49,90)\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"10000ms\" dur=\"1000ms\" attributeName=\"x\" "
        + "from=\"490.0\" to=\"340.0\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"10000ms\" dur=\"1000ms\" attributeName=\"y\" "
        + "from=\"50.0\" to=\"50.0\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"10000ms\" dur=\"1000ms\" attributeName=\"height\""
        + " from=\"30\" to=\"30\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"10000ms\" dur=\"1000ms\" attributeName=\"width\" "
        + "from=\"20\" to=\"20\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"10000ms\" dur=\"1000ms\" attributeName=\"rgb\" "
        + "from=\"(0,49,90)\" to=\"(0,49,90)\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"9900ms\" dur=\"100ms\" attributeName=\"x\" "
        + "from=\"490.0\" to=\"490.0\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"9900ms\" dur=\"100ms\" attributeName=\"y\" "
        + "from=\"50.0\" to=\"50.0\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"9900ms\" dur=\"100ms\" attributeName=\"height\" "
        + "from=\"30\" to=\"30\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"9900ms\" dur=\"100ms\" attributeName=\"width\" "
        + "from=\"20\" to=\"20\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"9900ms\" dur=\"100ms\" attributeName=\"rgb\" "
        + "from=\"(0,49,90)\" to=\"(0,49,90)\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"8900ms\" dur=\"1000ms\" attributeName=\"x\" "
        + "from=\"490.0\" to=\"490.0\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"8900ms\" dur=\"1000ms\" attributeName=\"y\" "
        + "from=\"240.0\" to=\"50.0\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"8900ms\" dur=\"1000ms\" attributeName=\"height\" "
        + "from=\"30\" to=\"30\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"8900ms\" dur=\"1000ms\" attributeName=\"width\" "
        + "from=\"20\" to=\"20\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"8900ms\" dur=\"1000ms\" attributeName=\"rgb\" "
        + "from=\"(0,49,90)\" to=\"(0,49,90)\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"5700ms\" dur=\"3200ms\" attributeName=\"x\" "
        + "from=\"490.0\" to=\"490.0\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"5700ms\" dur=\"3200ms\" attributeName=\"y\" "
        + "from=\"240.0\" to=\"240.0\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"5700ms\" dur=\"3200ms\" attributeName=\"height\" "
        + "from=\"30\" to=\"30\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"5700ms\" dur=\"3200ms\" attributeName=\"width\" "
        + "from=\"20\" to=\"20\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"5700ms\" dur=\"3200ms\" attributeName=\"rgb\" "
        + "from=\"(0,49,90)\" to=\"(0,49,90)\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"4700ms\" dur=\"1000ms\" attributeName=\"x\" "
        + "from=\"490.0\" to=\"490.0\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"4700ms\" dur=\"1000ms\" attributeName=\"y\" "
        + "from=\"50.0\" to=\"240.0\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"4700ms\" dur=\"1000ms\" attributeName=\"height\" "
        + "from=\"30\" to=\"30\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"4700ms\" dur=\"1000ms\" attributeName=\"width\" "
        + "from=\"20\" to=\"20\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"4700ms\" dur=\"1000ms\" attributeName=\"rgb\" "
        + "from=\"(0,49,90)\" to=\"(0,49,90)\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"4600ms\" dur=\"100ms\" attributeName=\"x\" "
        + "from=\"490.0\" to=\"490.0\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"4600ms\" dur=\"100ms\" attributeName=\"y\" "
        + "from=\"50.0\" to=\"50.0\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"4600ms\" dur=\"100ms\" attributeName=\"height\" "
        + "from=\"30\" to=\"30\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"4600ms\" dur=\"100ms\" attributeName=\"width\" "
        + "from=\"20\" to=\"20\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"4600ms\" dur=\"100ms\" attributeName=\"rgb\" "
        + "from=\"(0,49,90)\" to=\"(0,49,90)\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"3600ms\" dur=\"1000ms\" attributeName=\"x\" "
        + "from=\"190.0\" to=\"490.0\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"3600ms\" dur=\"1000ms\" attributeName=\"y\" "
        + "from=\"50.0\" to=\"50.0\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"3600ms\" dur=\"1000ms\" attributeName=\"height\" "
        + "from=\"30\" to=\"30\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"3600ms\" dur=\"1000ms\" attributeName=\"width\" "
        + "from=\"20\" to=\"20\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"3600ms\" dur=\"1000ms\" attributeName=\"rgb\" "
        + "from=\"(0,49,90)\" to=\"(0,49,90)\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"3500ms\" dur=\"100ms\" attributeName=\"x\" "
        + "from=\"190.0\" to=\"190.0\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"3500ms\" dur=\"100ms\" attributeName=\"y\" "
        + "from=\"50.0\" to=\"50.0\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"3500ms\" dur=\"100ms\" attributeName=\"height\""
        + " from=\"30\" to=\"30\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"3500ms\" dur=\"100ms\" attributeName=\"width\" "
        + "from=\"20\" to=\"20\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"3500ms\" dur=\"100ms\" attributeName=\"rgb\" "
        + "from=\"(0,49,90)\" to=\"(0,49,90)\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"2500ms\" dur=\"1000ms\" attributeName=\"x\" "
        + "from=\"190.0\" to=\"190.0\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"2500ms\" dur=\"1000ms\" attributeName=\"y\" "
        + "from=\"180.0\" to=\"50.0\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"2500ms\" dur=\"1000ms\" attributeName=\"height\" "
        + "from=\"30\" to=\"30\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"2500ms\" dur=\"1000ms\" attributeName=\"width\" "
        + "from=\"20\" to=\"20\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"2500ms\" dur=\"1000ms\" attributeName=\"rgb\" "
        + "from=\"(0,49,90)\" to=\"(0,49,90)\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"100ms\" dur=\"0ms\" attributeName=\"x\" "
        + "from=\"190.0\" to=\"190.0\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"100ms\" dur=\"0ms\" attributeName=\"y\" "
        + "from=\"180.0\" to=\"180.0\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"100ms\" dur=\"0ms\" attributeName=\"height\""
        + " from=\"30\" to=\"30\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"100ms\" dur=\"0ms\" attributeName=\"width\" "
        + "from=\"20\" to=\"20\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"100ms\" dur=\"0ms\" attributeName=\"rgb\" "
        + "from=\"(0,49,90)\" to=\"(0,49,90)\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"100ms\" dur=\"2400ms\" attributeName=\"x\" "
        + "from=\"190.0\" to=\"190.0\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"100ms\" dur=\"2400ms\" attributeName=\"y\" "
        + "from=\"180.0\" to=\"180.0\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"100ms\" dur=\"2400ms\" attributeName=\"height\""
        + " from=\"30\" to=\"30\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"100ms\" dur=\"2400ms\" attributeName=\"width\" "
        + "from=\"20\" to=\"20\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"100ms\" dur=\"2400ms\" attributeName=\"rgb\" "
        + "from=\"(0,49,90)\" to=\"(0,49,90)\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "</rect>\n"
        + "<rect id=\"disk2\" x=\"467.0\" y=\"210.0\" width=\"65.0\" height=\"30.0\" "
        + "fill=\"rgb(0,255,0)\" visibility=\"visible\">\n"
        + "<animate attributeType=\"xml\" begin=\"22500ms\" dur=\"7700ms\" attributeName=\"x\" "
        + "from=\"467.0\" to=\"467.0\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"22500ms\" dur=\"7700ms\" attributeName=\"y\" "
        + "from=\"210.0\" to=\"210.0\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"22500ms\" dur=\"7700ms\" attributeName=\"height\""
        + " from=\"30\" to=\"30\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"22500ms\" dur=\"7700ms\" attributeName=\"width\" "
        + "from=\"65\" to=\"65\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"22500ms\" dur=\"7700ms\" attributeName=\"rgb\" "
        + "from=\"(0,255,0)\" to=\"(0,255,0)\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"21700ms\" dur=\"800ms\" attributeName=\"x\" "
        + "from=\"467.0\" to=\"467.0\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"21700ms\" dur=\"800ms\" attributeName=\"y\" "
        + "from=\"210.0\" to=\"210.0\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"21700ms\" dur=\"800ms\" attributeName=\"height\" "
        + "from=\"30\" to=\"30\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"21700ms\" dur=\"800ms\" attributeName=\"width\""
        + " from=\"65\" to=\"65\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"21700ms\" dur=\"800ms\" attributeName=\"rgb\" "
        + "from=\"(6,247,41)\" to=\"(0,255,0)\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"20700ms\" dur=\"1000ms\" attributeName=\"x\" "
        + "from=\"467.0\" to=\"467.0\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"20700ms\" dur=\"1000ms\" attributeName=\"y\""
        + " from=\"50.0\" to=\"210.0\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"20700ms\" dur=\"1000ms\" attributeName=\"height\""
        + " from=\"30\" to=\"30\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"20700ms\" dur=\"1000ms\" attributeName=\"width\""
        + " from=\"65\" to=\"65\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"20700ms\" dur=\"1000ms\" attributeName=\"rgb\" "
        + "from=\"(6,247,41)\" to=\"(6,247,41)\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"20600ms\" dur=\"100ms\" attributeName=\"x\" "
        + "from=\"467.0\" to=\"467.0\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"20600ms\" dur=\"100ms\" attributeName=\"y\" "
        + "from=\"50.0\" to=\"50.0\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"20600ms\" dur=\"100ms\" attributeName=\"height\" "
        + "from=\"30\" to=\"30\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"20600ms\" dur=\"100ms\" attributeName=\"width\""
        + " from=\"65\" to=\"65\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"20600ms\" dur=\"100ms\" attributeName=\"rgb\" "
        + "from=\"(6,247,41)\" to=\"(6,247,41)\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"19600ms\" dur=\"1000ms\" attributeName=\"x\" "
        + "from=\"317.0\" to=\"467.0\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"19600ms\" dur=\"1000ms\" attributeName=\"y\" "
        + "from=\"50.0\" to=\"50.0\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"19600ms\" dur=\"1000ms\" attributeName=\"height\""
        + " from=\"30\" to=\"30\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"19600ms\" dur=\"1000ms\" attributeName=\"width\" "
        + "from=\"65\" to=\"65\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"19600ms\" dur=\"1000ms\" attributeName=\"rgb\""
        + " from=\"(6,247,41)\" to=\"(6,247,41)\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"19500ms\" dur=\"100ms\" attributeName=\"x\""
        + " from=\"317.0\" to=\"317.0\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"19500ms\" dur=\"100ms\" attributeName=\"y\" "
        + "from=\"50.0\" to=\"50.0\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"19500ms\" dur=\"100ms\" attributeName=\"height\""
        + " from=\"30\" to=\"30\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"19500ms\" dur=\"100ms\" attributeName=\"width\" "
        + "from=\"65\" to=\"65\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"19500ms\" dur=\"100ms\" attributeName=\"rgb\" "
        + "from=\"(6,247,41)\" to=\"(6,247,41)\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"18500ms\" dur=\"1000ms\" attributeName=\"x\" "
        + "from=\"317.0\" to=\"317.0\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"18500ms\" dur=\"1000ms\" attributeName=\"y\" "
        + "from=\"240.0\" to=\"50.0\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"18500ms\" dur=\"1000ms\" attributeName=\"height\""
        + " from=\"30\" to=\"30\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"18500ms\" dur=\"1000ms\" attributeName=\"width\""
        + " from=\"65\" to=\"65\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"18500ms\" dur=\"1000ms\" attributeName=\"rgb\""
        + " from=\"(6,247,41)\" to=\"(6,247,41)\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"8900ms\" dur=\"9600ms\" attributeName=\"x\" "
        + "from=\"317.0\" to=\"317.0\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"8900ms\" dur=\"9600ms\" attributeName=\"y\" "
        + "from=\"240.0\" to=\"240.0\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"8900ms\" dur=\"9600ms\" attributeName=\"height\" "
        + "from=\"30\" to=\"30\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"8900ms\" dur=\"9600ms\" attributeName=\"width\""
        + " from=\"65\" to=\"65\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"8900ms\" dur=\"9600ms\" attributeName=\"rgb\""
        + " from=\"(6,247,41)\" to=\"(6,247,41)\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"7900ms\" dur=\"1000ms\" attributeName=\"x\" "
        + "from=\"317.0\" to=\"317.0\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"7900ms\" dur=\"1000ms\" attributeName=\"y\" "
        + "from=\"50.0\" to=\"240.0\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"7900ms\" dur=\"1000ms\" attributeName=\"height\" "
        + "from=\"30\" to=\"30\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"7900ms\" dur=\"1000ms\" attributeName=\"width\" "
        + "from=\"65\" to=\"65\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"7900ms\" dur=\"1000ms\" attributeName=\"rgb\""
        + " from=\"(6,247,41)\" to=\"(6,247,41)\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"7800ms\" dur=\"100ms\" attributeName=\"x\" "
        + "from=\"317.0\" to=\"317.0\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"7800ms\" dur=\"100ms\" attributeName=\"y\" "
        + "from=\"50.0\" to=\"50.0\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"7800ms\" dur=\"100ms\" attributeName=\"height\" "
        + "from=\"30\" to=\"30\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"7800ms\" dur=\"100ms\" attributeName=\"width\" "
        + "from=\"65\" to=\"65\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"7800ms\" dur=\"100ms\" attributeName=\"rgb\" "
        + "from=\"(6,247,41)\" to=\"(6,247,41)\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"6800ms\" dur=\"1000ms\" attributeName=\"x\" "
        + "from=\"167.0\" to=\"317.0\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"6800ms\" dur=\"1000ms\" attributeName=\"y\" "
        + "from=\"50.0\" to=\"50.0\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"6800ms\" dur=\"1000ms\" attributeName=\"height\""
        + " from=\"30\" to=\"30\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"6800ms\" dur=\"1000ms\" attributeName=\"width\""
        + " from=\"65\" to=\"65\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"6800ms\" dur=\"1000ms\" attributeName=\"rgb\" "
        + "from=\"(6,247,41)\" to=\"(6,247,41)\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"6700ms\" dur=\"100ms\" attributeName=\"x\" "
        + "from=\"167.0\" to=\"167.0\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"6700ms\" dur=\"100ms\" attributeName=\"y\" "
        + "from=\"50.0\" to=\"50.0\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"6700ms\" dur=\"100ms\" attributeName=\"height\""
        + " from=\"30\" to=\"30\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"6700ms\" dur=\"100ms\" attributeName=\"width\""
        + " from=\"65\" to=\"65\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"6700ms\" dur=\"100ms\" attributeName=\"rgb\" "
        + "from=\"(6,247,41)\" to=\"(6,247,41)\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"5700ms\" dur=\"1000ms\" attributeName=\"x\" "
        + "from=\"167.0\" to=\"167.0\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"5700ms\" dur=\"1000ms\" attributeName=\"y\" "
        + "from=\"210.0\" to=\"50.0\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"5700ms\" dur=\"1000ms\" attributeName=\"height\" "
        + "from=\"30\" to=\"30\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"5700ms\" dur=\"1000ms\" attributeName=\"width\" "
        + "from=\"65\" to=\"65\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"5700ms\" dur=\"1000ms\" attributeName=\"rgb\""
        + " from=\"(6,247,41)\" to=\"(6,247,41)\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"100ms\" dur=\"0ms\" attributeName=\"x\" "
        + "from=\"167.0\" to=\"167.0\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"100ms\" dur=\"0ms\" attributeName=\"y\" "
        + "from=\"210.0\" to=\"210.0\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"100ms\" dur=\"0ms\" attributeName=\"height\" "
        + "from=\"30\" to=\"30\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"100ms\" dur=\"0ms\" attributeName=\"width\""
        + " from=\"65\" to=\"65\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"100ms\" dur=\"0ms\" attributeName=\"rgb\" "
        + "from=\"(6,247,41)\" to=\"(6,247,41)\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"100ms\" dur=\"5600ms\" attributeName=\"x\" "
        + "from=\"167.0\" to=\"167.0\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"100ms\" dur=\"5600ms\" attributeName=\"y\" "
        + "from=\"210.0\" to=\"210.0\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"100ms\" dur=\"5600ms\" attributeName=\"height\" "
        + "from=\"30\" to=\"30\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"100ms\" dur=\"5600ms\" attributeName=\"width\""
        + " from=\"65\" to=\"65\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"100ms\" dur=\"5600ms\" attributeName=\"rgb\""
        + " from=\"(6,247,41)\" to=\"(6,247,41)\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "</rect>\n"
        + "<rect id=\"disk3\" x=\"445.0\" y=\"240.0\" width=\"110.0\" height=\"30.0\" "
        + "fill=\"rgb(0,255,0)\" visibility=\"visible\">\n"
        + "<animate attributeType=\"xml\" begin=\"16100ms\" dur=\"14100ms\" attributeName=\"x\""
        + " from=\"445.0\" to=\"445.0\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"16100ms\" dur=\"14100ms\" attributeName=\"y\""
        + " from=\"240.0\" to=\"240.0\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"16100ms\" dur=\"14100ms\" "
        + "attributeName=\"height\" from=\"30\" to=\"30\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"16100ms\" dur=\"14100ms\""
        + " attributeName=\"width\" from=\"110\" to=\"110\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"16100ms\" dur=\"14100ms\" "
        + "attributeName=\"rgb\" from=\"(0,255,0)\" to=\"(0,255,0)\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"15300ms\" dur=\"800ms\" "
        + "attributeName=\"x\" from=\"445.0\" to=\"445.0\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"15300ms\" dur=\"800ms\""
        + " attributeName=\"y\" from=\"240.0\" to=\"240.0\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"15300ms\" dur=\"800ms\""
        + " attributeName=\"height\" from=\"30\" to=\"30\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"15300ms\" dur=\"800ms\" "
        + "attributeName=\"width\" from=\"110\" to=\"110\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"15300ms\" dur=\"800ms\" "
        + "attributeName=\"rgb\" from=\"(11,45,175)\" to=\"(0,255,0)\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"14300ms\" dur=\"1000ms\" "
        + "attributeName=\"x\" from=\"445.0\" to=\"445.0\" fill=\"freeze\" "
        + "visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"14300ms\" dur=\"1000ms\" "
        + "attributeName=\"y\" from=\"50.0\" to=\"240.0\" fill=\"freeze\""
        + " visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"14300ms\" dur=\"1000ms\" "
        + "attributeName=\"height\" from=\"30\" to=\"30\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"14300ms\" dur=\"1000ms\" "
        + "attributeName=\"width\" from=\"110\" to=\"110\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"14300ms\" dur=\"1000ms\" "
        + "attributeName=\"rgb\" from=\"(11,45,175)\" to=\"(11,45,175)\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"14200ms\" dur=\"100ms\" "
        + "attributeName=\"x\" from=\"445.0\" to=\"445.0\" fill=\"freeze\" "
        + "visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"14200ms\" dur=\"100ms\" "
        + "attributeName=\"y\" from=\"50.0\" to=\"50.0\" fill=\"freeze\" "
        + "visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"14200ms\" dur=\"100ms\" "
        + "attributeName=\"height\" from=\"30\" to=\"30\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"14200ms\" dur=\"100ms\" "
        + "attributeName=\"width\" from=\"110\" to=\"110\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"14200ms\" dur=\"100ms\" "
        + "attributeName=\"rgb\" from=\"(11,45,175)\" to=\"(11,45,175)\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"13200ms\" dur=\"1000ms\" "
        + "attributeName=\"x\" from=\"145.0\" to=\"445.0\" fill=\"freeze\" "
        + "visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"13200ms\" dur=\"1000ms\" "
        + "attributeName=\"y\" from=\"50.0\" to=\"50.0\" fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"13200ms\" dur=\"1000ms\" "
        + "attributeName=\"height\" from=\"30\" to=\"30\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"13200ms\" dur=\"1000ms\" "
        + "attributeName=\"width\" from=\"110\" to=\"110\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"13200ms\" dur=\"1000ms\" "
        + "attributeName=\"rgb\" from=\"(11,45,175)\" to=\"(11,45,175)\" "
        + "fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"13100ms\" dur=\"100ms\" "
        + "attributeName=\"x\" from=\"145.0\" to=\"145.0\" fill=\"freeze\""
        + " visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"13100ms\" dur=\"100ms\""
        + " attributeName=\"y\" from=\"50.0\" to=\"50.0\" fill=\"freeze\""
        + " visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"13100ms\" dur=\"100ms\" "
        + "attributeName=\"height\" from=\"30\" to=\"30\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"13100ms\" dur=\"100ms\" "
        + "attributeName=\"width\" from=\"110\" to=\"110\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"13100ms\" dur=\"100ms\" "
        + "attributeName=\"rgb\" from=\"(11,45,175)\" to=\"(11,45,175)\" "
        + "fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"12100ms\" dur=\"1000ms\" "
        + "attributeName=\"x\" from=\"145.0\" to=\"145.0\" fill=\"freeze\" "
        + "visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"12100ms\" dur=\"1000ms\" "
        + "attributeName=\"y\" from=\"240.0\" to=\"50.0\" fill=\"freeze\" "
        + "visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"12100ms\" dur=\"1000ms\" "
        + "attributeName=\"height\" from=\"30\" to=\"30\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"12100ms\" dur=\"1000ms\" "
        + "attributeName=\"width\" from=\"110\" to=\"110\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"12100ms\" dur=\"1000ms\" "
        + "attributeName=\"rgb\" from=\"(11,45,175)\" to=\"(11,45,175)\" "
        + "fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"100ms\" dur=\"0ms\""
        + " attributeName=\"x\" from=\"145.0\" to=\"145.0\" fill=\"freeze\" "
        + "visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"100ms\" dur=\"0ms\" "
        + "attributeName=\"y\" from=\"240.0\" to=\"240.0\" fill=\"freeze\" "
        + "visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"100ms\" dur=\"0ms\" "
        + "attributeName=\"height\" from=\"30\" to=\"30\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"100ms\" dur=\"0ms\" "
        + "attributeName=\"width\" from=\"110\" to=\"110\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"100ms\" dur=\"0ms\" "
        + "attributeName=\"rgb\" from=\"(11,45,175)\" to=\"(11,45,175)\" "
        + "fill=\"freeze\" visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"100ms\" dur=\"12000ms\" "
        + "attributeName=\"x\" from=\"145.0\" to=\"145.0\" fill=\"freeze\" "
        + "visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"100ms\" dur=\"12000ms\" "
        + "attributeName=\"y\" from=\"240.0\" to=\"240.0\" fill=\"freeze\" "
        + "visibility=\"visible\" />\n"
        + "<animate attributeType=\"xml\" begin=\"100ms\" dur=\"12000ms\" "
        + "attributeName=\"height\" from=\"30\" to=\"30\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"100ms\" dur=\"12000ms\" "
        + "attributeName=\"width\" from=\"110\" to=\"110\" fill=\"freeze\"/>\n"
        + "<animate attributeType=\"xml\" begin=\"100ms\" dur=\"12000ms\" "
        + "attributeName=\"rgb\" from=\"(11,45,175)\" to=\"(11,45,175)\" "
        + "fill=\"freeze\" visibility=\"visible\" />\n"
        + "</rect>\n"
        + "\n"
        + "</svg>", fileContent);
  }

}
